# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: kaixo, i'm smith.
email: seimith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a collection of some random thoughts, #TILs, and some tips for myself.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://seimith.github.io" # the base hostname & protocol for your site
twitter_username: themcsuth
github_username:  seimith

# Build settings
markdown: kramdown
